# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Enable the Corne OLED Display and custom status screen
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Enable mouse / pointing device support
CONFIG_ZMK_POINTING=y

# Optional nice-view-gem settings
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE=y
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE_MAX=120
CONFIG_NICE_VIEW_GEM_ANIMATION=y
CONFIG_NICE_VIEW_GEM_ANIMATION_MS=960

# Set deep sleep to 30 minutes
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Change board name
CONFIG_ZMK_KEYBOARD_NAME="Cole's Corne"

# Windows compatibility fixes
CONFIG_BT_CTLR_PHY_2M=n
